/**
 * WorkIndex — Service Category & Questionnaire Configuration
 * ============================================================
 * AUTO-GENERATED by WorkIndex Admin CMS.
 * DO NOT edit manually — use the admin panel to modify.
 * Generated: 2026-05-09T07:13:21.173Z
 */
 
const WI_SERVICES = {
 
  // ─── Master list of all service categories ──────────────
  list: [],
 
  // ─── Quick lookup maps (auto-generated from list) ───────
  get labels() {
    const m = {};
    this.list.forEach(s => m[s.value] = s.label);
    return m;
  },
  get colors() {
    const m = {};
    this.list.forEach(s => m[s.value] = s.color);
    return m;
  },
  get icons() {
    const m = {};
    this.list.forEach(s => m[s.value] = s.icon);
    return m;
  },
 
  // ─── Landing page search aliases ────────────────────────
  searchAliases: {},
 
  // ─── Credit cost per service ─────────────────────────────
  creditCost: {},
 
  // ─── Max approaches per request ──────────────────────────
  maxApproaches: {},
 
  // ─── Questionnaire (nested structure) ────────────────────
  questionnaire: {
 
    serviceSelection: {
      id: 'service', key: 'service',
      type: 'service-picker',
      title: 'What service do you need?',
      subtitle: 'Select the category that best matches your requirement',
      required: true,
      useServiceList: true,
    },
 
    byService: {},
 
    common: {
    "service_location_type": {
        "id": "service_location_type",
        "key": "service_location_type",
        "type": "single",
        "required": true,
        "title": "Where do you need the service?",
        "options": [
            {
                "value": "online",
                "label": "Online / Remotely",
                "icon": "💻",
                "desc": "Share documents digitally"
            },
            {
                "value": "my-location",
                "label": "At my location",
                "icon": "🏠",
                "desc": "Professional comes to me"
            },
            {
                "value": "professional-office",
                "label": "At professional's office",
                "icon": "🏢",
                "desc": "I visit their office"
            }
        ]
    },
    "full_address": {
        "id": "full_address",
        "key": "full_address",
        "type": "address",
        "required": true,
        "title": "Enter your address",
        "fields": {
            "building": {
                "label": "Flat / Building / House No.",
                "placeholder": "e.g. 4B, Sunrise Apartments",
                "required": true
            },
            "area": {
                "label": "Area / Street / Locality",
                "placeholder": "e.g. Koramangala 5th Block",
                "required": true
            },
            "pincode": {
                "label": "Pincode",
                "placeholder": "e.g. 560095",
                "required": true,
                "autoFillTrigger": true
            },
            "city": {
                "label": "City",
                "placeholder": "e.g. Bengaluru",
                "required": true,
                "autoFilled": true
            },
            "state": {
                "label": "State",
                "placeholder": "Select your state",
                "required": true,
                "type": "select",
                "autoFilled": true
            },
            "landmark": {
                "label": "Landmark (optional)",
                "placeholder": "e.g. Near Indiranagar metro",
                "required": false
            }
        }
    },
    "client_location": {
        "id": "client_location",
        "key": "client_location",
        "type": "address",
        "required": true,
        "title": "Where are you based?",
        "fields": {
            "pincode": {
                "label": "Pincode",
                "placeholder": "e.g. 560095",
                "required": true,
                "autoFillTrigger": true
            },
            "city": {
                "label": "City",
                "placeholder": "e.g. Bengaluru",
                "required": true,
                "autoFilled": true
            },
            "state": {
                "label": "State",
                "placeholder": "Select state",
                "required": true,
                "type": "select",
                "autoFilled": true
            }
        }
    },
    "urgency": {
        "id": "urgency",
        "key": "urgency",
        "type": "single",
        "required": true,
        "title": "When do you need this done?",
        "options": [
            {
                "value": "immediate",
                "label": "Immediately (within 24 hours)",
                "icon": "🔴"
            },
            {
                "value": "2-3days",
                "label": "Within 2–3 days",
                "icon": "🟠"
            },
            {
                "value": "week",
                "label": "Within a week",
                "icon": "🟡"
            },
            {
                "value": "month",
                "label": "Within a month",
                "icon": "🟢"
            },
            {
                "value": "flexible",
                "label": "Flexible / No rush",
                "icon": "🔵"
            }
        ]
    },
    "budget": {
        "id": "budget",
        "key": "budget",
        "type": "slider",
        "required": false,
        "title": "What is your budget?",
        "subtitle": "Professionals will send quotes based on this",
        "min": 1000,
        "max": 100000,
        "step": 500,
        "format": "₹{value}",
        "defaultValue": 5000
    },
    "description": {
        "id": "description",
        "key": "description",
        "type": "textarea",
        "required": true,
        "title": "Describe your requirement",
        "subtitle": "More detail helps professionals give accurate quotes",
        "placeholder": "Please describe what you need in detail...",
        "minLength": 20,
        "maxLength": 1000,
        "validation": "Minimum 20 characters required"
    },
    "preferred_professional": {
        "id": "preferred_professional",
        "key": "preferred_professional",
        "type": "single",
        "required": false,
        "title": "What type of professional do you prefer?",
        "options": [
            {
                "value": "individual_ca",
                "label": "Individual CA / Freelancer",
                "icon": "👤",
                "desc": "Personal attention, often more affordable"
            },
            {
                "value": "firm",
                "label": "CA Firm / Agency",
                "icon": "🏢",
                "desc": "Team support, established firm"
            },
            {
                "value": "no_preference",
                "label": "No preference",
                "icon": "🤷",
                "desc": "Best quote wins"
            }
        ]
    },
    "contact_method": {
        "id": "contact_method",
        "key": "contact_method",
        "type": "single",
        "required": true,
        "title": "How should professionals contact you?",
        "options": [
            {
                "value": "platform_chat",
                "label": "Chat on WorkIndex",
                "icon": "💬",
                "desc": "Professionals message you here"
            },
            {
                "value": "phone",
                "label": "Phone call / WhatsApp",
                "icon": "📞",
                "desc": "They call or WhatsApp you directly"
            },
            {
                "value": "email",
                "label": "Email",
                "icon": "✉️",
                "desc": "They email you"
            },
            {
                "value": "any",
                "label": "Any method is fine",
                "icon": "✅"
            }
        ]
    }
},
 
    expert: [
    {
        "id": "expert_services",
        "key": "servicesOffered",
        "type": "multi",
        "required": true,
        "title": "What services do you offer?",
        "subtitle": "Select all that apply",
        "useServiceList": true
    },
    {
        "id": "expert_specialization",
        "key": "specialization",
        "type": "single",
        "required": true,
        "title": "What is your primary specialization?",
        "options": [
            {
                "value": "Chartered Accountant",
                "label": "Chartered Accountant (CA)",
                "icon": "🎓"
            },
            {
                "value": "Cost Accountant",
                "label": "Cost Accountant (CMA)",
                "icon": "🎓"
            },
            {
                "value": "Company Secretary",
                "label": "Company Secretary (CS)",
                "icon": "🎓"
            },
            {
                "value": "Tax Consultant",
                "label": "Tax Consultant",
                "icon": "📄"
            },
            {
                "value": "GST Consultant",
                "label": "GST Consultant",
                "icon": "🧾"
            },
            {
                "value": "Bookkeeper",
                "label": "Bookkeeper / Accountant",
                "icon": "📊"
            },
            {
                "value": "Photographer",
                "label": "Photographer",
                "icon": "📷"
            },
            {
                "value": "Web Developer",
                "label": "Web / App Developer",
                "icon": "💻"
            },
            {
                "value": "Other",
                "label": "Other Professional",
                "icon": "🔧"
            }
        ]
    },
    {
        "id": "expert_experience",
        "key": "yearsOfExperience",
        "type": "single",
        "required": true,
        "title": "How many years of experience do you have?",
        "options": [
            {
                "value": "0-1",
                "label": "Less than 1 year",
                "icon": "🌱"
            },
            {
                "value": "1-3",
                "label": "1 – 3 years",
                "icon": "📈"
            },
            {
                "value": "3-5",
                "label": "3 – 5 years",
                "icon": "📈"
            },
            {
                "value": "5-10",
                "label": "5 – 10 years",
                "icon": "⭐"
            },
            {
                "value": "10+",
                "label": "More than 10 years",
                "icon": "🏆"
            }
        ]
    },
    {
        "id": "expert_location",
        "key": "serviceLocationType",
        "type": "single",
        "required": true,
        "title": "Where do you prefer to work?",
        "options": [
            {
                "value": "online",
                "label": "Online / Remotely only",
                "icon": "💻",
                "desc": "Work with clients anywhere in India"
            },
            {
                "value": "local",
                "label": "Local (in-person preferred)",
                "icon": "📍",
                "desc": "Prefer meeting clients face to face"
            },
            {
                "value": "both",
                "label": "Both online and in-person",
                "icon": "🌐",
                "desc": "Flexible depending on the client"
            }
        ]
    },
    {
        "id": "expert_location_details",
        "key": "expert_location_details",
        "type": "address",
        "required": true,
        "title": "Where are you based?",
        "subtitle": "Enter your pincode — city and state will be filled automatically",
        "fields": {
            "pincode": {
                "label": "Pincode",
                "placeholder": "e.g. 560095",
                "required": true,
                "autoFillTrigger": true
            },
            "city": {
                "label": "City",
                "placeholder": "e.g. Bengaluru",
                "required": true,
                "autoFilled": true
            },
            "state": {
                "label": "State",
                "placeholder": "Select state",
                "required": true,
                "type": "select",
                "autoFilled": true
            }
        }
    },
    {
        "id": "expert_bio",
        "key": "bio",
        "type": "textarea",
        "required": true,
        "title": "Tell clients about yourself",
        "subtitle": "Your bio appears on your public profile",
        "placeholder": "e.g. I am a Chartered Accountant with 8 years of experience...",
        "minLength": 50,
        "maxLength": 500,
        "validation": "Minimum 50 characters required"
    }
],
 
  },
 
  // ─── Answer tag formatters (for browse cards) ────────────
  answerTagFormatters: {

  },
 
};
 
Object.freeze(WI_SERVICES);
